<fieldset class="fieldset create info">
    <legend class="legend">
        <span>Mobbex</span>
    </legend>
    <br>
    <div class="field field-mbbx_cuit required">
        <label for="mbbx_cuit" class="label">
            <span>Mobbex CUIT</span>
        </label>

        <div class="control">
            <input type="text" title="Mobbex CUIT" value="" name="mbbx_cuit" id="mbbx_cuit" autocomplete="off" aria-required="true" class="input-text vendor-field">
        </div>
    </div>
</fieldset>